version: '2'
services:

 openvpn-server:
     image: "kylemanna/openvpn"
     ports:
         - "1194:1194/udp"
     cap_add:
         - NET_ADMIN
     volumes:
         - ovpn-data:/etc/openvpn

volumes:
    ovpn-data:
        driver: local
